"""empty message

Revision ID: 177d1d01e7d7
Revises: 07c28252220e
Create Date: 2021-06-10 17:50:11.027783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177d1d01e7d7'
down_revision = '07c28252220e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
