"""empty message

Revision ID: 547e49c689e2
Revises: 177210a67104
Create Date: 2021-07-02 21:41:32.127670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547e49c689e2'
down_revision = '177210a67104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('covid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('state_code', sa.String(length=64), nullable=True),
    sa.Column('confirmed', sa.String(length=64), nullable=True),
    sa.Column('active', sa.String(length=64), nullable=True),
    sa.Column('recovered', sa.String(length=64), nullable=True),
    sa.Column('deaths', sa.String(length=64), nullable=True),
    sa.Column('deltaconfirmed', sa.String(length=64), nullable=True),
    sa.Column('deltarecovered', sa.String(length=64), nullable=True),
    sa.Column('deltadeaths', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeseries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newcases', sa.String(length=64), nullable=True),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('covid_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['covid_id'], ['covid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeseries')
    op.drop_table('covid')
    # ### end Alembic commands ###
