"""initial migration

Revision ID: 714e44aae7bd
Revises: 
Create Date: 2021-06-04 20:23:42.954222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714e44aae7bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mob_no', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['mob_no'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'mob_no')
    # ### end Alembic commands ###
